-- Banco de dados Projeto Academia 
CREATE DATABASE GYM_SYSTEM;
USE GYM_SYSTEM;
-- DROP DATABASE GYM_SYSTEM1;
-- CRIAÇÃO DAS TABELAS 

CREATE TABLE IF NOT EXISTS USUARIO (
ID_USUARIO INT AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
USUARIO VARCHAR(20) NOT NULL,
SENHA VARCHAR(16) NOT NULL,
CONF_SENHA VARCHAR(16) NOT NULL,
CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO)
)ENGINE INNODB;

INSERT INTO USUARIO (NOME, USUARIO, SENHA, CONF_SENHA) VALUES ('LEONARDO VASSALO', 'LEONARDOVS', '123456', '123456');
INSERT INTO USUARIO (NOME, USUARIO, SENHA, CONF_SENHA) VALUES ('NAYARA SANTOS', 'NAYSTS', '123456', '123456');


SELECT *FROM USUARIO where NOME LIKE '%LEO%';




CREATE TABLE IF NOT EXISTS PLANO (
ID_PLAN INT AUTO_INCREMENT,
NOME_PLAN VARCHAR(50) NOT NULL,
VALOR_PLAN FLOAT (3.2) NOT NULL,
CONSTRAINT PK_ID_PLAN PRIMARY KEY (ID_PLAN)
) ENGINE INNODB;

CREATE TABLE IF NOT EXISTS ENDERECO (
ID_END INT AUTO_INCREMENT,
ENDERECO VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL,
BAIRRO VARCHAR (100) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
CEP VARCHAR(9) NOT NULL,
COMPLEMENTO VARCHAR(100),
CONSTRAINT PK_ID_END PRIMARY KEY (ID_END)
) ENGINE INNODB;

CREATE TABLE IF NOT EXISTS CLIENTE(
ID_CLI INT AUTO_INCREMENT,
NOME_CLI VARCHAR(100) NOT NULL,
SEXO_CLI CHAR(1) NOT NULL COMMENT 'M - MASCULINO/ F - FEMININO',
DTA_NASC_CLI DATE NOT NULL,
CPF_CLI VARCHAR(11) NOT NULL,
CELULAR VARCHAR(10)NOT NULL,
ID_END INT,
CONSTRAINT PK_ID_CLI PRIMARY KEY (ID_CLI),
CONSTRAINT FK_ID_END FOREIGN KEY (ID_END) REFERENCES ENDERECO (ID_END),
CONSTRAINT CK_SEXO_CLI CHECK  (SEXO_CLI IN ('F', 'M'))
)ENGINE INNODB;

select *from CLIENTE;
 
CREATE TABLE IF NOT EXISTS PROFESSOR(
ID_PROF INT AUTO_INCREMENT,
NOME_PROF VARCHAR(100) NOT NULL,
SEXO_PROF CHAR(1) NOT NULL COMMENT 'M - MASCULINO/ F - FEMININO',
DTA_NASC_PROF DATE NOT NULL,
CPF_PROF VARCHAR(11) NOT NULL,
CREF INT NOT NULL,
ID_END INT,
CONSTRAINT PK_ID_PROF PRIMARY KEY (ID_PROF),
CONSTRAINT FK_ID_END_PROF FOREIGN KEY (ID_END) REFERENCES ENDERECO (ID_END),
CONSTRAINT CK_SEXO_PROF CHECK  (SEXO_PROF IN ('F', 'M'))
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS MATRICULA (
ID_MAT INT AUTO_INCREMENT,
DTA_INICIO_MAT DATE NOT NULL,
DTA_FIM_MAT DATE,
ID_CLI INT,
ID_PROF INT,
ID_PLAN INT,
CONSTRAINT PK_ID_MAT PRIMARY KEY (ID_MAT),
CONSTRAINT FK_ID_CLI FOREIGN KEY (ID_CLI) REFERENCES CLIENTE (ID_CLI),
CONSTRAINT FK_ID_PROF FOREIGN KEY (ID_PROF) REFERENCES PROFESSOR (ID_PROF),
CONSTRAINT FK_ID_PLAN FOREIGN KEY (ID_PLAN) REFERENCES PLANO (ID_PLAN)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS ENTRADA (
ID_ENTRADA INT AUTO_INCREMENT,
HORA_ENTRADA TIME NOT NULL,
HORA_SAIDA TIME,
DATA_FREQ DATE NOT NULL, 
ID_MAT INT,
CONSTRAINT PK_ID_ENTRADA PRIMARY KEY (ID_ENTRADA),
CONSTRAINT FK_ID_MAT FOREIGN KEY (ID_MAT) REFERENCES MATRICULA (ID_MAT)
)ENGINE INNODB;

SELECT *FROM cliente;